services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
    restart: unless-stopped
    env_file:
      - .env
