/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as GeneralRouteImport } from './app/general'
import { Route as ProtectedRouteImport } from './app/_protected'
import { Route as AuthRouteImport } from './app/_auth'
import { Route as IndexRouteImport } from './app/index'
import { Route as ProtectedProfileRouteImport } from './app/_protected/profile'
import { Route as ProtectedAppealDraftRouteImport } from './app/_protected/appeal-draft'
import { Route as AuthRegisterRouteImport } from './app/_auth/register'
import { Route as AuthLoginRouteImport } from './app/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './app/_auth/forgot-password'
import { Route as ProtectedChatIndexRouteImport } from './app/_protected/chat/index'
import { Route as ApiAuthLoginRouteImport } from './app/api/auth/login'
import { Route as ProtectedChatIdRouteImport } from './app/_protected/chat/$id'
import { Route as AuthRegisterVerifyRouteImport } from './app/_auth/register.verify'
import { Route as AuthForgotPasswordVerifyRouteImport } from './app/_auth/forgot-password.verify'
import { Route as AuthForgotPasswordResetRouteImport } from './app/_auth/forgot-password.reset'

const GeneralRoute = GeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppealDraftRoute = ProtectedAppealDraftRouteImport.update({
  id: '/appeal-draft',
  path: '/appeal-draft',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedChatIndexRoute = ProtectedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedChatIdRoute = ProtectedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthRegisterVerifyRoute = AuthRegisterVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRegisterRoute,
} as any)
const AuthForgotPasswordVerifyRoute =
  AuthForgotPasswordVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthForgotPasswordRoute,
  } as any)
const AuthForgotPasswordResetRoute = AuthForgotPasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthForgotPasswordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/general': typeof GeneralRoute
  '/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRouteWithChildren
  '/appeal-draft': typeof ProtectedAppealDraftRoute
  '/profile': typeof ProtectedProfileRoute
  '/forgot-password/reset': typeof AuthForgotPasswordResetRoute
  '/forgot-password/verify': typeof AuthForgotPasswordVerifyRoute
  '/register/verify': typeof AuthRegisterVerifyRoute
  '/chat/$id': typeof ProtectedChatIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/chat/': typeof ProtectedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/general': typeof GeneralRoute
  '/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRouteWithChildren
  '/appeal-draft': typeof ProtectedAppealDraftRoute
  '/profile': typeof ProtectedProfileRoute
  '/forgot-password/reset': typeof AuthForgotPasswordResetRoute
  '/forgot-password/verify': typeof AuthForgotPasswordVerifyRoute
  '/register/verify': typeof AuthRegisterVerifyRoute
  '/chat/$id': typeof ProtectedChatIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/chat': typeof ProtectedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/general': typeof GeneralRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRouteWithChildren
  '/_protected/appeal-draft': typeof ProtectedAppealDraftRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_auth/forgot-password/reset': typeof AuthForgotPasswordResetRoute
  '/_auth/forgot-password/verify': typeof AuthForgotPasswordVerifyRoute
  '/_auth/register/verify': typeof AuthRegisterVerifyRoute
  '/_protected/chat/$id': typeof ProtectedChatIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/_protected/chat/': typeof ProtectedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/general'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/appeal-draft'
    | '/profile'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/register/verify'
    | '/chat/$id'
    | '/api/auth/login'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/general'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/appeal-draft'
    | '/profile'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/register/verify'
    | '/chat/$id'
    | '/api/auth/login'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/general'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/appeal-draft'
    | '/_protected/profile'
    | '/_auth/forgot-password/reset'
    | '/_auth/forgot-password/verify'
    | '/_auth/register/verify'
    | '/_protected/chat/$id'
    | '/api/auth/login'
    | '/_protected/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  GeneralRoute: typeof GeneralRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/general': {
      id: '/general'
      path: '/general'
      fullPath: '/general'
      preLoaderRoute: typeof GeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/appeal-draft': {
      id: '/_protected/appeal-draft'
      path: '/appeal-draft'
      fullPath: '/appeal-draft'
      preLoaderRoute: typeof ProtectedAppealDraftRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/chat/': {
      id: '/_protected/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ProtectedChatIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/chat/$id': {
      id: '/_protected/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ProtectedChatIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/register/verify': {
      id: '/_auth/register/verify'
      path: '/verify'
      fullPath: '/register/verify'
      preLoaderRoute: typeof AuthRegisterVerifyRouteImport
      parentRoute: typeof AuthRegisterRoute
    }
    '/_auth/forgot-password/verify': {
      id: '/_auth/forgot-password/verify'
      path: '/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof AuthForgotPasswordVerifyRouteImport
      parentRoute: typeof AuthForgotPasswordRoute
    }
    '/_auth/forgot-password/reset': {
      id: '/_auth/forgot-password/reset'
      path: '/reset'
      fullPath: '/forgot-password/reset'
      preLoaderRoute: typeof AuthForgotPasswordResetRouteImport
      parentRoute: typeof AuthForgotPasswordRoute
    }
  }
}

interface AuthForgotPasswordRouteChildren {
  AuthForgotPasswordResetRoute: typeof AuthForgotPasswordResetRoute
  AuthForgotPasswordVerifyRoute: typeof AuthForgotPasswordVerifyRoute
}

const AuthForgotPasswordRouteChildren: AuthForgotPasswordRouteChildren = {
  AuthForgotPasswordResetRoute: AuthForgotPasswordResetRoute,
  AuthForgotPasswordVerifyRoute: AuthForgotPasswordVerifyRoute,
}

const AuthForgotPasswordRouteWithChildren =
  AuthForgotPasswordRoute._addFileChildren(AuthForgotPasswordRouteChildren)

interface AuthRegisterRouteChildren {
  AuthRegisterVerifyRoute: typeof AuthRegisterVerifyRoute
}

const AuthRegisterRouteChildren: AuthRegisterRouteChildren = {
  AuthRegisterVerifyRoute: AuthRegisterVerifyRoute,
}

const AuthRegisterRouteWithChildren = AuthRegisterRoute._addFileChildren(
  AuthRegisterRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAppealDraftRoute: typeof ProtectedAppealDraftRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedChatIdRoute: typeof ProtectedChatIdRoute
  ProtectedChatIndexRoute: typeof ProtectedChatIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppealDraftRoute: ProtectedAppealDraftRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedChatIdRoute: ProtectedChatIdRoute,
  ProtectedChatIndexRoute: ProtectedChatIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  GeneralRoute: GeneralRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
